#! /bin/bash

TYPE="mbox" #default is respondable mailbox, for application pass in "am"
SRC=
OUTPUT_DIR="$PWD/"

#parse more complicated command. Expected input is "-{opt}"
#default is above Arguements. Below is all options available:
#o - output directory, relative to $HOME
#s - source mailbox link
#t - type : typically "mbox" for mail, or "am" for applicable patches

OPTSTRING="o:s:t:h"

while getopts ${OPTSTRING} opt; do
	case ${opt} in
		o)
			OUTPUT_DIR="$HOME/${OPTARG}/"
			;;
		s)
			SRC="${OPTARG}"
			;;
		t)
			TYPE=${OPTARG}
			;;
		h)
			printf "o : OUTPUT_DIR\ns : SOURCE\nt : TYPE\n"
			echo "See file for more details"
			exit
			;;
	esac
done

#This WILL fail if no SRC is provided with the -s option
COMMAND="b4 $TYPE $SRC -o $OUTPUT_DIR"

echo $COMMAND
eval $COMMAND
