#! /bin/bash
TESTING_REPO=~/testing

source $TESTING_REPO/examples/example_scripts/host/load_config

#parse more complicated command. Expected input is "-{opt}"
#default is above Arguements. Below is all the options available:
#a - ARCH - MUST come before "-k"
#A - ACCEL - Which QEMU accelerator we want to use (can do many like default)
#b - BOOT_FILE - Path to boot for the kernel to run (absolute path)
#e - EXTRA - Path to directory for attaching (absolute path) - must be mounted
#p - BOOT_PARAMS - Early boot params (if list, must be surrounded by "")
#k - Path to kernel (build directory)
#K - Path to kernel (absolute path)
#q - Override qemu-kvm with qemu for the given arch
#Q - Overrited qemu command with this command
#r - Root filesystem type to mount
#R - Root path (i.e. /dev/sda1)
#c - Number of cpu cores
#m - RAM provided
#d - Display type (usually none, curses, or gtk - See QEMU man page)
#M - Monitor type (usually none, vc, or stdio - See QEMU man page)
#s - Serial type (usually none, vc, or stdio - See QEMU man page)
#i - Iterface (see QEMU man page)

OPTSTRING="a:A:b:e:p:u:k:K:q:Q:r:R:c:m:d:M:s:i:h"

while getopts ${OPTSTRING} opt; do
	case ${opt} in
		a)
			ARCH=${OPTARG}
			;;
		A)
			ACCEL=${OPTARG}
			;;
		b)
			BOOT_FILE=${OPTARG}
			;;
		e)
			EXTRA=${OPTARG}
			;;
		p)
			BOOT_PARAMS=${OPTARG}
			;;
		u)
			USER=${OPTARG}
			;;
		k)
			KERNEL_PATH="${OPTARG}/arch/$ARCH/boot/bzImage"
			;;
		K)
			KERNEL_PATH=${OPTARG}
			;;
		r)
			ROOTFS=${OPTARG}
			;;
		R)
			RPATH=${OPTARG}
			;;
		q)
			QEMU="qemu-system-${ARCH}"
			;;
		Q)
			QEMU=${OPTARG}
			;;
		c)
			CPUS=${OPTARG}
			;;
		m)
			MEMORY=${OPTARG}
			;;
		d)
			DISPLAY=${OPTARG}
			;;
		M)
			MONITOR=${OPTARG}
			;;
		s)
			SERIAL=${OPTARG}
			;;
		i)
			INTERFACE=${OPTARG}
			;;
		h)
			printf "a : ARCH\nA : Accelerator\nb : BOOT_FILE absolute path\ne : EXTRA absolute path\np : BOOT_PARAMS\nk : Kernel BUILD_DIR\nK : absolute Kernel path\nr : ROOTFS\nR : Root path\nq : Use qemu-system-ARCH\nQ : QEMU command\nc : CPUS\nm : MEMORY\nd : DISPLAY type\nM : MONITOR type\ns : SERIAL device\ni : Interface\nu : Add custom parameters\n"
			echo "See file for more details"
			exit
			;;
	esac
done

#Simple qemu command. We need the \ to separate each argument otherwise qemu gets confused. Customize as desired.
COMMAND="$QEMU \
     -kernel $KERNEL_PATH \
     -drive format=raw,file=$BOOT_FILE,if=$INTERFACE \
     -append 'root=$RPATH rw rootfstype=$ROOTFS console=ttSy0 $BOOT_PARAMS' \
     -accel $ACCEL \
     -m $MEMORY \
     -s \
     -serial $SERIAL \
     -monitor $MONITOR \
     -display $DISPLAY \
     -smp cores=$CPUS \
     -object memory-backend-ram,size=$MEMORY,id=m$NUMA_ID \
     -numa node,cpus=0-$((CPUS - 1)),nodeid=$NUMA_ID,memdev=m$NUMA_ID \
     -net nic -net user,hostfwd=tcp::10022-:22 \
     $USER \
     -virtfs local,path=$EXTRA,mount_tag=host0,security_model=passthrough,id=host0" #for getting access to files, anything in the path directory will work
#    -machine accel=kvm (this can be used if kvm hardware acceleration is supported)

echo $COMMAND
eval $COMMAND
