# Default configuration for qemu_test
ARCH="x86_64"
KERNEL_PATH="$HOME/kernel/compiled/arch/x86_64/boot/bzImage"
BOOT_FILE="image.raw"
ROOTFS="ext4"
MEMORY="1G"
CPUS="1"
NUMA_ID="0"
SERIAL="stdio"
MONITOR="vc"
DISPLAY="curses"
EXTRA="mkosi.extra"
BOOT_PARAMS="nokaslr printk.synchronous=1"
QEMU="qemu-kvm"
ACCEL="kvm -accel tcg"
INTERFACE="ide"
RPATH="/dev/sda1"
USER=""
