#! /bin/bash
ARGUMENTS="bzImage"
BUILD_DIR="compiled/"
COMPILER="ccache gcc"
ARCH="x86_64"
THREADS="8"
# i.e. building a full kernel, using ccache for the x86 compiler
# We don't care about ccache for other systems b/c not building frequently
# enough

#parse more complicated make command, default is above
#Arguements:
#1 - files to make, bzImage to cmdline if unsure
#2 - compiler, gcc if unsure (without ARCH might be weird)
#3 - ARCH, x86_64 if unsure
if [ $# -gt 0 ];
then
	ARGUMENTS=$1
fi
if [ $# -gt 1 ];
then
	COMPILER=$2
fi
if [ $# -gt 2 ];
then
	ARCH=$3
fi
make -j$THREADS O=$BUILD_DIR $ARGUMENTS CC="$COMPILER" ARCH=$ARCH
