# Default configuration for qemu_test
# Rename this to 'qemu_test.conf' for load_configs to work
ARCH="aarch64"
KERNEL_PATH="$HOME/kernel/arm64/arch/arm64/boot/Image"
BOOT_FILE="$HOME/images/mkosi/arm64/image.raw"
ROOTFS="ext4"
MEMORY="1G"
CPUS="1"
NUMA_ID="0"
SERIAL="stdio"
MONITOR="vc"
DISPLAY="gtk"
EXTRA="$HOME/testing/mkosi.extra"
BOOT_PARAMS="nokaslr printk.synchronous=1"
QEMU="qemu-system-aarch64"
ACCEL="kvm -accel tcg"
INTERFACE="none,id=hd0"
RPATH="/dev/vda1"
CONSOLE="ttyAMA0"
# Pass 'help' instead of an identifier for more details
USER="-M virt -cpu cortex-a53 -device virtio-blk-device,drive=hd0"
