#! /bin/bash
TESTING_REPO=~/testing

source $TESTING_REPO/examples/example_scripts/host/load_config

#Options:
#k - Kernel name (relative to SOURCE_DIR)
#m - module location (relative to $HOME)
#s - Source Directory (can generally be thought of as the kernel build dir)
#    relative to ($HOME/kernel)

OPTSTRING="k:m:h"

while getopts ${OPTSTRING} opt; do
	case ${opt} in
		k)
			KERNEL=${OPTARG}
			;;
		m)
			MODULES_DIR=${OPTARG}
			;;
		h)
			printf "k : KERNEL\nm : MODULES_DIR\n"
			echo "See file for more details"
			exit
			;;
	esac
done

echo $KERNEL

#MAKE SURE that we have /[USER]/.config/gdb/gdbinit
#with add-auto-load-safe-path /[safepath]
COMMAND="gdb \
	-s '$KERNEL' -q \
	-ex 'target remote localhost:1234' \
	-ex 'lx-symbols $MODULES_DIR' \
	-ex 'c'"
echo $COMMAND
eval $COMMAND
