#! /bin/bash
TESTING_REPO=~/testing

source $TESTING_REPO/examples/example_scripts/host/load_config

# This is paired with the ssh networking in QEMU
#1 - log onto the guest
#2 - mount the shared directory
#3 - run the "example_ssh_setup" script

# p - port
OPTSTRING="p:h"
while getopts ${OPTSTRING} opt; do
	case ${opt} in
		p)
			PORT=${OPTARG}
			;;
		h)
			printf "p : Port\n"
			echo "See file for more details"
			exit
			;;
	esac
done

ssh root@localhost -p$PORT -o StrictHostKeyChecking=no
