#! /bin/bash
TESTING_REPO=~/testing

source $TESTING_REPO/examples/example_scripts/host/load_config

OPTSTRING="c:C:d:h"

while getopts ${OPTSTRING} opt; do
	case ${opt} in
		c)
			CONFIG="~/.gitconfig_${OPTARG}"
			;;
		C)
			CONFIG=${OPTARG}
			;;
		d)
			DEST=${OPTARG}
			;;
		h)
			printf "c : CONFIG\nC : CONFIG_PATH\nd : DEST_PATH\n"
			echo "See file for more details"
			exit
			;;
	esac
done

COMMAND="cp ${CONFIG} ${DEST}"
echo $COMMAND
eval $COMMAND
