# Default configuration for qemu_test
ARCH="aarch64"
KERNEL_PATH="$TESTING_REPO/kernel/barebones/arch/arm64/boot/Image"
BOOT_FILE="image.raw"
DISK_FORMAT="raw"
ROOTFS="ext4"
MEMORY="1G"
CPUS="1"
NUMA_ID="0"
SERIAL="stdio"
MONITOR="vc"
DISPLAY="none"
EXTRA="mkosi.extra"
BOOT_PARAMS="nokaslr printk.synchronous=1 earlycon=pl011,0x9000000"
QEMU="qemu-system-aarch64"
ACCEL="hvf -accel tcg"
INTERFACE="none,id=hd0"
IP_PORT="10022-:22"
RPATH="/dev/vda1"
CONSOLE="ttyAMA0"
USER="-M virt -cpu host -device virtio-blk-device,drive=hd0 -s"
