[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main,universe

[Output]
Format=disk

[Build]
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.packagecache
BuildDirectory=mkosi.builddir
Environment=SYSTEMD_REPART_OVERRIDE_FSTYPE_ROOT=ext4
WithNetwork=yes
Incremental=yes

[Content]
Packages=
	acl
	attr
	automake
	bash-completion
	bc
	ca-certificates
	coreutils
	cpio
	dbench
	diffutils
	apt
	dump
	dwarves
	e2fsprogs
	findutils
	fio
	gawk
	gcc
	gdb
	libgdbm-dev
	git
	grep
	gzip
	hostname
	hwloc
	indent
	jq
	kbd
	linux-headers-generic
	linux-tools-common
	kexec-tools
	kmod
	less
	libacl1-dev
	libaio-dev
	libcap-dev
	libtool
	liburing-dev
	uuid-dev
	lvm2
	make
	man-db
	nano
	neovim
	network-manager
	openssh-server
	linux-tools-generic
	procps
	psmisc
	python3
	quota
	dpkg
	rustc
	sed
	socat
	sqlite3
	strace
	stress-ng
	sudo
	systemd
	tmux
	tree
	udev
	udftools
	util-linux
	valgrind
	vim
	xfsprogs
	zip
	zstd
	xfslibs-dev
	btrfs-progs
	exfatprogs
	f2fs-tools
	ocfs2-tools
	xfsdump
Autologin=yes
SELinuxRelabel=no
Bootloader=none
Bootable=no

KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=default
